name: React CI

on:
  push:
    branches: [ "main2" ]
  #pull_request:
    #branches: [ "main2" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: sudo rm -rfv /var/www/html/build
    - run: sudo mv build /var/www/html/

      #with:
        #source: 'build'
        #target: '/var/www/html/'
